  AP/Drivetrain[m
  AP/Drivetrain-Code[m
  MC/2025Template[m
  NM/ReefscapePrototyping[m
  SL/BunnyBotsExtraAutos[m
* [32mZG/ChoreoAutos[m
  main[m
  [31mremotes/origin/AP/Drivetrain-Code[m
  [31mremotes/origin/AP/claw-intake[m
  [31mremotes/origin/AP/robotgo-basic-motor[m
  [31mremotes/origin/AT/BunnyBots2024Autos[m
  [31mremotes/origin/BunnyBots2024[m
  [31mremotes/origin/BunnyBotsCompMain[m
  [31mremotes/origin/Bunnybots_Drivetrain_Test[m
  [31mremotes/origin/DS/basicMotor[m
  [31mremotes/origin/HA/BunnyBotsIntakeTesting[m
  [31mremotes/origin/HA/intake_Pivot[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/JGT/basic_motor[m
  [31mremotes/origin/JR[m
  [31mremotes/origin/MC/2025Template[m
  [31mremotes/origin/MC/BunnyBotsCodebaseRework[m
  [31mremotes/origin/MC/BunnyBotsDrivetrainTest[m
  [31mremotes/origin/MC/BunnyBotsTemplate[m
  [31mremotes/origin/MC/CommandBased2024[m
  [31mremotes/origin/MCSL/PhotonVisionMain[m
  [31mremotes/origin/NM/BunnybotsSysID[m
  [31mremotes/origin/NM/ReefscapePrototyping[m
  [31mremotes/origin/NM/SwerveSysID[m
  [31mremotes/origin/NX-Double-Clock-Elevator[m
  [31mremotes/origin/NX-Elevator[m
  [31mremotes/origin/RG/IntakeSkeletonCode[m
  [31mremotes/origin/RKG/basicMotor[m
  [31mremotes/origin/SL/BunnyBotsExtraAutos[m
  [31mremotes/origin/SL/IntegratedVision[m
  [31mremotes/origin/SL/NewPhotonVisionTesting[m
  [31mremotes/origin/SL/PhotonVisionTesting[m
  [31mremotes/origin/SL/basic_motor[m
  [31mremotes/origin/ZAG/basic_motor[m
  [31mremotes/origin/ZG/ChoreoAutos[m
  [31mremotes/origin/ZR/Intake[m
  [31mremotes/origin/main[m
